--1. Create table 'Waterlines'

  CREATE TABLE "WATERLINES" 
   (	"ANNO_DIAM" VARCHAR2(255 BYTE), 
	"COMPKEY" NUMBER(38,0), 
	"COMPTYPE" NUMBER(38,0), 
	"DIAMETER" VARCHAR2(255 BYTE), 
	"DRAW" NUMBER(38,0), 
	"FEATURE_ID" VARCHAR2(25 BYTE), 
	"LEAD_MAIN_" NUMBER(38,0), 
	"MATERIAL" VARCHAR2(8 BYTE), 
	"PRIMARYINDEX" NUMBER(38,0), 
	"PROJECT" VARCHAR2(255 BYTE), 
	"PR_ZONE" VARCHAR2(4 BYTE), 
	"STATUS" VARCHAR2(3 BYTE), 
	"SYMCODE" NUMBER(38,0), 
	"SYMCODE2" NUMBER(38,0), 
	"TILE" VARCHAR2(4 BYTE), 
	"WNM_TYPE" VARCHAR2(8 BYTE), 
	"YEAR_INSTA" NUMBER(38,0), 
	"AUTOCAD_ELEVATION" NUMBER(38,0), 
	"BULK_LOAD" NUMBER(38,0), 
	"GEOM" "MDSYS"."SDO_GEOMETRY" 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--2. Insert geometry metadata for Waterlines table

INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid) VALUES ('WATERLINES',	'GEOM',	MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',0,5000000,0.05),MDSYS.SDO_DIM_ELEMENT('Y',7500000,12500000,0.05)),	2277);

--3. Create spatial index for Waterlines table

 CREATE INDEX "WATERLINES_SG1" ON "WATERLINES" ("GEOM") 
   INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;

--4. Create a Temp_IDs table

CREATE TABLE "TEMP_IDS" 
   ("FEATURE_ID" VARCHAR2(25 BYTE));
